### ISSUE TITLE
Whitelist sizes to resize

### ISSUE THREAD

**Issue by michaelhayman** [sagidM/s3-resizer#10]
It would be quite annoying if someone was to create various sizes of different images.

Is there a way to white list only a few specific image sizes?

**Comment by sagidM** [comment]
Michael, the possibility of creating as many images of people want worries me sometimes too.
Right now there is no whitelist. However, I have an idea of providing an optional variable where they could specify whitelist image sizes.
I will think about this within the next couple of weeks keeping this issue open and eventually come up with something.
Thank you for your question.

**Comment by nelsonamaya82** [comment]
This definitely would be a great enhancement. @sagidM have you came up with something regarding it?

Thanks!

**Comment by nelsonamaya82** [comment]
@sagidM I created a PR to close this ticket, please review it.

**Comment by sagidM** [comment]
In release since [3.1.0](https://github.com/sagidM/s3-resizer/releases/tag/3.1.0)
