### ISSUE TITLE
What mean "Missing Authentication Token" ?

### ISSUE THREAD

**Issue by jonneyless** [sagidM/s3-resizer#12]
I have one file "https://qooapp-image.s3-ap-southeast-1.amazonaws.com/1.jpg".

when I use https://qooapp-image.s3-ap-southeast-1.amazonaws.com/200x200/1.jpg, it redirect to "https://rjmbvlnp5h.execute-api.ap-southeast-1.amazonaws.com/qooapp-image-resize/qooapp-image-resize/200x200/1.jpg", and say "Missing Authentication Token".

but open "https://qooapp-image.s3-ap-southeast-1.amazonaws.com/200x200/1.jpg" again, it ok.

**Comment by jonneyless** [comment]
Resolved

**Comment by sagidM** [comment]
It could be helpful for others if you could share the solution.
Anyway, it is cool to see it resolved so quickly.
