### ISSUE TITLE
index.handler is undefined or not exported

### ISSUE THREAD

**Issue by dhavalk-simform** [sagidM/s3-resizer#15]
I followed readme file and I've done everything that @sagidM said in the readme file.

node version is: 12.x
Handler: index.handler
.zip file: s3-resizer-3.1.0.zip (download zip from your repo.)

Still, I'm getting below error when I run the test.

test json is 

```
{
  "queryStringParameters": {
    "path": "150x150/engg.jpg"
  }
}
```

![lambda_error](https://user-images.githubusercontent.com/62876889/78970576-3ae13480-7b27-11ea-863b-55e5ab6c7913.png)

**Comment by jinjuezhou** [comment]
I  have the same question now, how to solve

**Comment by sagidM** [comment]
@jinjuezhou make sure you followed the instructions.
When uploading the project, upload the zip archive, not a single file.
Now package.json is required as it has `"type": "module"`, and the archive contains it.
