### ISSUE TITLE
npm module error

### ISSUE THREAD

**Issue by bsweaty** [sagidM/s3-resizer#2]
ran through the install steps, ran into an issue when running my test:

`{
  "errorMessage": "The module '/var/task/node_modules/sharp/build/Release/sharp.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 48. This version of Node.js requires\nNODE_MODULE_VERSION 57. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).",
  "errorType": "Error",
  "stackTrace": [
    "NODE_MODULE_VERSION 48. This version of Node.js requires",
    "NODE_MODULE_VERSION 57. Please try re-compiling or re-installing",
    "the module (for instance, using `npm rebuild` or `npm install`).",
    "Object.Module._extensions..node (module.js:681:18)",
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)",
    "Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:10:15)",
    "Module._compile (module.js:652:30)",
    "Object.Module._extensions..js (module.js:663:10)",
    "Module.load (module.js:565:32)"
  ]
}`

**Comment by sagidM** [comment]
Hi Brian,

Thank you for opening.
Could you tell me, please, what the assembly you are using?
Was that from https://github.com/sagidM/s3-resizer/releases
Or you download a zip file https://github.com/sagidM/s3-resizer/archive/master.zip
Giving the answer to either option will help!

**Comment by mxnr** [comment]
Hey @sagidM! 
Just got the same error, i am using zip from latest 2.0.0 release

**Comment by mxnr** [comment]
Tried to download master, run `npm install` with node 8.10.0, push it to lambda, but now i'm getting: 
```
Unable to import module 'index': Error
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
```

**Comment by sagidM** [comment]
Oh, okay.
That's interesting.
Anyway I am going to update README with latest instructions.
So I will test everything asap.

**Comment by bsweaty** [comment]
![image](https://user-images.githubusercontent.com/2700879/52421226-e2d91900-2ab0-11e9-94e5-206be398b715.png)

this is the one. thanks @sagidM

**Comment by sagidM** [comment]
Okay guys...
Seems the release you have downloaded ([2.0.0 tag](https://github.com/sagidM/s3-resizer/releases/tag/2.0.0)) was only for **NodeJS 6.10**, not for **8.10**.

I have changed the description of that one and added a new release [2.0.1](https://github.com/sagidM/s3-resizer/releases/tag/2.0.1).
Yes, now we have 2 versions!
I think in the next releases I keep only **NodeJS 8**, but since we have users who might use version 6, let it be for now.

FAQ how to build:
http://sharp.pixelplumbing.com/en/stable/install/#aws-lambda

**Comment by sagidM** [comment]
@bsweaty @mxnr 
One more thing that has to be mentioned:
You may get the error **Access Denied**.
To fix that you need to **Your bucket -> Public access settings -> Edit**.
Then uncheck the corresponding fields:
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/13490595/52712238-0a464f00-2fa5-11e9-905d-675488b0901b.png">
(I do not use **Remove** so I have kept that one)
Of course I will put this in **README** soon.

> Info https://stackoverflow.com/a/53348340
