### ISSUE TITLE
  "errorMessage": "Error: Cannot find module 'sharp'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",

### ISSUE THREAD

**Issue by 8secz-johndpope** [sagidM/s3-resizer#20]
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'sharp'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'sharp'",
    "Require stack:",
    "- /var/task/index.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:1015:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)",
    "    at Module.load (internal/modules/cjs/loader.js:879:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
    "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
}

**Comment by 8secz-johndpope** [comment]
for clarity - is the s3 function supposed to look like this?
or like the index.js in the layer?


<img width="1048" alt="Screen Shot 2021-01-11 at 4 22 33 pm" src="https://user-images.githubusercontent.com/50567111/104149135-40a6d600-5429-11eb-8073-6bef163f45dc.png">




![Uploading Screen Shot 2021-01-11 at 4.23.19 pm.png…]()

**Comment by sagidM** [comment]
@8secz-johndpope no, absolutely not. Please take a look on the Releases page https://github.com/sagidM/s3-resizer/releases 
It is written in the readme.
I am closing this issue. If I did not get you right, don't hesitate to reopen it
