### ISSUE TITLE
AWS end support for Node.js 16

### ISSUE THREAD

**Issue by xni06** [sagidM/s3-resizer#23]
I received the following email from AWS - do you intend to rebuild using 16?

> Hello,
> 
> We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Node.js 12 runtime.
> 
> We are ending support for Node.js 12 in AWS Lambda. This follows Node.js 12 End-Of-Life (EOL) reached on April 30, 2022 [1].
> 
> As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting November 14, 2022, Lambda will no longer apply security patches and other updates to the Node.js 12 runtime used by Lambda functions, and functions using Node.js 12 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Node.js 12 runtime. Starting December 14, 2022, you will no longer be able to update existing functions using the Node.js 12 runtime.
> 
> We recommend that you upgrade your existing Node.js 12 functions to Node.js 16 before November 14, 2022.

**Comment by sagidM** [comment]
Sure. Soon I am going to update the version to NodeJS 16 and 18.
But I believe the current version can also be run on those without any changes.

A new version of NodeJS is coming out within 10 days from the date of writing this

**Comment by xni06** [comment]
> Sure. Soon I am going to update the version to NodeJS 16 and 18.

Any luck?

**Comment by sagidM** [comment]
@xni06 hey, thank you for pinging me.
Yes, I updated s3-resizer, it was one of the biggest update ever.
It contains the latest libraries, syntax and uses streams instead of buffers
https://github.com/sagidM/s3-resizer/releases/tag/4.0.0
