### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by nicopenaredondo** [sagidM/s3-resizer#4]
Upon testing it. The lambda test shows this error.

![image](https://user-images.githubusercontent.com/3615451/63238001-f55db780-c276-11e9-81c2-befef854c93b.png)

**Comment by solonalbuquerque** [comment]
In the IAM Manager, go to you IAM function
And add AWSLambdaExecute and AmazonAPIGatewayInvokeFullAccess in politics

**Comment by sagidM** [comment]
@nicopenaredondo I think the problem is that you did not give some permissions.
The exception is probably thrown on putting an image to your bucket.
Make sure you followed `permission`_(CTRL+F)_ sections on the `README.md` page.

**Comment by zpetukhov** [comment]
@nicopenaredondo I faced with the same error.
In my case, the reason was: I not only uploaded to s3, but also used 'Tagging' key.
So I have to add "s3:PutObjectTagging" to the policy.
You can try to allow all S3 actions (s3:*) in the policy. Then check if it works. Then you can narrow access back.

**Comment by sagidM** [comment]
Since the solution was proposed. Though I actually believe following the README, you should have no problem.
