### ISSUE TITLE
AWS end support for Node.js 8.x

### ISSUE THREAD

**Issue by xni06** [sagidM/s3-resizer#8]
I received the following email from AWS - do you intend to rebuild using 10?

---

> Hello,
> 
> We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Node.js 8.10, which will reach its EOL at the end of 2019.
> 
> > What’s happening?
> 
> The Node community has decided to end support for Node.js 8.x on December 31, 2019 [1]. From this date forward, Node.js 8.x will stop receiving bug fixes, security updates, and/or performance improvements. To ensure that your new and existing functions run on a supported and secure runtime, language runtimes that have reached their EOL are deprecated in AWS [2].
> 
> For Node.js 8.x, there will be 2 stages to the runtime deprecation process:
> 
> 1. Disable Function Create – Beginning January 6, 2020, customers will no longer be able to create functions using Node.js 8.10
> 
> 2. Disable Function Update – Beginning February 3, 2020, customers will no longer be able to update functions using Node.js 8.10
> 
> After this period, both function creation and updates will be disabled permanently. However, existing Node 8.x functions will still be available to process invocation events.
> 
> > What do I need to do?
> 
> We encourage you to update all of your Node.js 8.10 functions to the newer available runtime version, Node.js 10.x[3]. You should test your functions for compatibility with the Node.js 10.x language version before applying changes to your production functions.

**Comment by sagidM** [comment]
@xni06, thank you for your question.
NodeJS 8 can be found in the Release page.
But at the same time, I have completely rebuilt s3-resizer for NodeJS 10.x

I will update the repository after in the following 2-3 days.

**Comment by xni06** [comment]
> @xni06, thank you for your question.
> NodeJS 8 can be found in the Release page.
> But at the same time, I have completely rebuilt s3-resizer for NodeJS 10.x
> I will update the repository after in the following 2-3 days.

Thanks @sagidM - any luck/update with the release?

**Comment by sagidM** [comment]
@xni06 thank you for reaching out.
I just released the latest updates for NodeJS 10x and 12x.
It seems there is no sense to maintain 8x and 10x versions anymore, so from now on I am more concentrate on 12x until the newer NodeJS comes.
https://github.com/sagidM/s3-resizer/releases/tag/3.0.0

I have tested everything. However, if you encounter any problem, please, let me know.

**Comment by sagidM** [comment]
Redirect in CloudFront caused https://github.com/sagidM/s3-resizer/issues/5 and https://github.com/sagidM/s3-resizer/issues/7
which made me fix it by adding Cache-Control
https://github.com/sagidM/s3-resizer/releases/tag/3.0.1

Seems everything is fine. I am closing the issue.
